/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ctgu.examsystem.rest;

import com.ctgu.examsystem.rest.dto.ClassDto;
import com.ctgu.examsystem.rest.dto.CreateClassRequest;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-21T15:25:47.161+08:00[Asia/Shanghai]")

@Validated
@Api(value = "class", description = "the class API")
public interface ClassApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "创建班级", nickname = "createClassInfo", notes = "", response = ClassDto.class, tags={ "class", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = ClassDto.class),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<ClassDto> createClassInfo(@ApiParam(value = "老师Id",required=true) @PathVariable("teacherRef") Long teacherRef,@ApiParam(value = "" ,required=true )  @Valid @RequestBody CreateClassRequest createClassRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"stuNumber\" : 6,  \"className\" : \"className\",  \"id\" : 0}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "删除指定班级", nickname = "deleteClass", notes = "", tags={ "class", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功"),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteClass(@ApiParam(value = "老师Id",required=true) @PathVariable("teacherRef") Long teacherRef,@ApiParam(value = "班级id",required=true) @PathVariable("id") Long id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "获取班级列表", nickname = "getClassList", notes = "", response = ClassDto.class, responseContainer = "List", tags={ "class", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = ClassDto.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<ClassDto>> getClassList(@ApiParam(value = "老师Id",required=true) @PathVariable("teacherRef") Long teacherRef) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"stuNumber\" : 6,  \"className\" : \"className\",  \"id\" : 0}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "获取指定班级详情", nickname = "getTeacherInfo", notes = "", response = ClassDto.class, tags={ "class", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = ClassDto.class),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ClassDto> getTeacherInfo(@ApiParam(value = "老师id",required=true) @PathVariable("teacherRef") Long teacherRef,@ApiParam(value = "班级Id",required=true) @PathVariable("id") Long id) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"stuNumber\" : 6,  \"className\" : \"className\",  \"id\" : 0}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "更新班级学生", nickname = "updateStudentsOfClass", notes = "", response = ClassDto.class, tags={ "c lass", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = ClassDto.class),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}/{id}/{studentRef}",
        produces = { "application/json" }, 
        method = RequestMethod.PATCH)
    default ResponseEntity<ClassDto> updateStudentsOfClass(@ApiParam(value = "老师id",required=true) @PathVariable("teacherRef") Long teacherRef,@ApiParam(value = "班级id",required=true) @PathVariable("id") Long id,@ApiParam(value = "学生id",required=true) @PathVariable("studentRef") Long studentRef,@NotNull @ApiParam(value = "操作[0:添加学生，1:删除学生]", required = true) @Valid @RequestParam(value = "operate", required = true) Integer operate) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"stuNumber\" : 6,  \"className\" : \"className\",  \"id\" : 0}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "更新班级信息", nickname = "updateTeacher", notes = "", response = ClassDto.class, tags={ "class", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = ClassDto.class),
        @ApiResponse(code = 404, message = "服务未找到", response = String.class) })
    @RequestMapping(value = "/class/{teacherRef}/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    default ResponseEntity<ClassDto> updateTeacher(@ApiParam(value = "老师Id",required=true) @PathVariable("teacherRef") Long teacherRef,@ApiParam(value = "班级Id",required=true) @PathVariable("id") Long id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody CreateClassRequest createClassRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"stuNumber\" : 6,  \"className\" : \"className\",  \"id\" : 0}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
