openapi: 3.0.0
info:
  title: 系统API文档
  description: C语言在线测评系统接口设计文档
  version: '0.1'
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '127.0.0.1:8080/'
    description: Development server

tags:
  - name: ExamSystem

paths:
  /question:
    post:
      tags:
        - question
      summary: 创建题目
      operationId: createQuestionInfo
      parameters:
        - in: query
          name: teacherRef
          required: true
          description: 老师Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuestionRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到

  /question/{id}:
    patch:
      tags:
        - question
      summary: 更新题目信息
      operationId: updateQuestion
      parameters:
        - in: path
          name: id
          required: true
          description: 题目Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuestionRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - question
      summary: 获取指定题目详情
      operationId: getQuestionInfo
      parameters:
        - in: path
          name: id
          required: true
          description: 班级Id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    delete:
      tags:
        - question
      summary: 删除指定题目
      operationId: deleteClass
      parameters:
        - in: path
          name: id
          required: true
          description: 班级id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到

  /question/{teacherRef}/{type}/{contextType}:
    get:
      tags:
        - question
      summary: 获取题目列表
      operationId: getQuestionListOfTeacher
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师Id
          schema:
            type: integer
            format: int64
        - in: path
          name: type
          required: true
          description: 题目类型(0.所有,1.判断正误,2.选择,3.填空题， 4.问答题, 5.编程题)
          schema:
            type: integer
            format: int32
        - in: path
          name: contextType
          required: true
          description: 内容类型查询
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到



  /ContextType/{teacherRef}:
    get:
      tags:
        - contextType
      summary: 获取题目类型
      operationId: getContextType
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContextTypeDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    post:
      tags:
        - contextType
      summary: 添加题目类型
      operationId: createContextType
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContextTypeRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextTypeDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到

    delete:
      tags:
        - contextType
      summary: 删除题目内容类型
      operationId: delContextType
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
        - in: query
          name: id
          required: true
          description: 主键
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到

components:
  schemas:
    QuestionDto:
      description: 题目详情
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 题目主键
        typeRef:
          description: 题目类型
          type: integer
          format: int32
        contextTypeRef:
          description: 题目内容类型
          type: integer
          format: int64
        qDescribe:
          description: 问题描述
          type: string
        aDescribe:
          description: 答案描述
          type: string
        score:
          description: 分数
          type: number
          format: 浮动
        teacherRef:
          description: 创建的老师id
          type: integer
          format: int64

    ContextTypeDto:
      description: 题目内容类型详情
      type: object
      properties:
        id:
          description: 题目内容类型主键
          type: integer
          format: int64
        contextDescribe:
          description: 描述
          type: string
        teacherRef:
          description: 创建用户Id
          type: integer
          format: int64

    CreateQuestionRequest:
      description: 创建题目详情对象
      type: object
      properties:
        typeRef:
          description: 题目类型
          type: integer
          format: int32
        contextTypeRef:
          description: 题目内容类型
          type: integer
          format: int64
        qDescribe:
          description: 问题描述
          type: string
        aDescribe:
          description: 答案描述
          type: string
        score:
          description: 分数
          type: number
          format: 浮动

    CreateContextTypeRequest:
      description: 创建题目内容类型详情对象
      type: object
      properties:
        contextDescribe:
          description: 题目内容类型
          type: string
