openapi: 3.0.0
info:
  title: 系统API文档
  description: C语言在线测评系统接口设计文档
  version: '0.1'
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '127.0.0.1:8080/'
    description: Development server

tags:
  - name: ExamSystem

paths:
  /examResult/{studentRef}:
    post:
      tags:
        - examResult
      summary: 创建考试结果
      operationId: createExamResultInfo
      parameters:
        - in: path
          name: studentRef
          required: true
          description: 学生Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExamResultRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamResultDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags: 
        - examResult
      summary: 获取该用户的所有考试结果信息
      parameters: 
        - in: path
          name: studentRef
          required: true
          description: 学生Id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExamResultDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    
  /examResult/{id}:
    patch:
      tags:
        - examResult
      summary: 更新考试结果信息
      operationId: updateExamResult
      parameters:
        - in: path
          name: id
          required: true
          description: 考试结果Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExamResultRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamResultDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - examResult
      summary: 获取指定考试结果详情
      operationId: getExamResultInfo
      parameters:
        - in: path
          name: id
          required: true
          description: 考试Id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamResultDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    delete:
      tags: 
        - examResult
      summary: 删除指定考试结果
      operationId: deleteExamResult
      parameters:
        - in: path
          name: id
          required: true
          description: 考试结果id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
  
 
components:
  schemas:
    ExamResultDto:
      description: 考试结果详情
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 考试结果主键
        answers:
          type: string
          description: 答案列表
        score:
          type: number
          format: 浮点
          description: 得分
        startTime:
          type: string
          description: 开始时间
        endTime:
          type: string
          description: 结束时间
          
    CreateExamResultRequest:
      description: 创建题目详情对象
      type: object
      properties:
        paperRef:
          description: 试卷Id
          type: integer
          format: int64
        answers:
          type: string
          description: 答案列表
        score:
          type: number
          format: 浮点
          description: 得分
        startTime:
          type: string
          description: 开始时间
        endTime:
          type: string
          description: 结束时间
          

