openapi: 3.0.0
info:
  title: 系统API文档
  description: C语言在线测评系统接口设计文档
  version: '0.1'
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '127.0.0.1:8080/'
    description: Development server

tags:
  - name: ExamSystem

paths:
  /paper/{teacherRef}:
    post:
      tags:
        - paper
      summary: 创建试卷
      operationId: createPaperInfo
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师Id
          schema:
            type: integer
            format: int64
        - in: query
          name: type
          required: true
          description: 状态[1.编辑中，2.已完成，3.已过期]
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaperRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - paper
      summary: 获取当前老师的试卷列表
      operationId: getPaperList
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师Id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: arry
                items:
                  $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    
  /paper/{id}:
    patch:
      tags:
        - paper
      summary: 更新试卷信息
      operationId: updatePaper
      parameters:
        - in: path
          name: id
          required: true
          description: 试卷Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaperRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - paper
      summary: 获取指定试卷详情
      operationId: getPaperInfo
      parameters:
        - in: path
          name: id
          required: true
          description: 试卷Id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    delete:
      tags: 
        - paper
      summary: 删除指定试卷
      operationId: deletePaper
      parameters:
        - in: path
          name: id
          required: true
          description: 试卷id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
  
   
  
  /paper/{teacherRef}/{type}:
    get:
      tags:
        - paper
      summary: 获取指定状态的试卷列表
      operationId: getPaperListOfType
      parameters:
        - in: path
          name: teacherRef
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
        - in: path
          name: type
          required: true
          description: 状态分类(1.编辑中，2.已完成，3.已过期)
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaperDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到 
 
components:
  schemas:
    PaperDto:
      description: 试卷详情
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 试卷主键
        paperName:
          description: 试卷名称
          type: string
        totalScore:
          description: 试卷总分
          type: number
          format: 浮点
        appointQuestions:
          description: 指定题目
          type: string
        startTime:
          description: 开始时间
          type: string
        endTime:
          description: 过期时间
          type: string
        totalTime:
          description: 考试时长
          type: integer
          format: int32
        type:
          description: 状态分类(0.编辑中，1.已完成，2.已过期)
          type: integer
          format: int32
          
    CreatePaperRequest:
      description: 创建试卷详情对象
      type: object
      properties:
        paperName:
          description: 试卷名称
          type: string
        totalScore:
          description: 试卷总分
          type: number
          format: 浮点
        appointQuestions:
          description: 指定题目
          type: string
        studentsRef:
          description: 考试学生
          type: string
        totalTime:
          description: 考试时长
          type: integer
          format: int32
        startTime:
          description: 开始时间
          type: string
        endTime:
          description: 过期时间
          type: string
        

