openapi: 3.0.0
info:
  title: 系统API文档
  description: C语言在线测评系统接口设计文档
  version: '0.1'
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '127.0.0.1:8080/'
    description: Development server

tags:
  - name: ExamSystem

paths:
  /teacher:
    post:
      tags:
        - teacher
      summary: 创建老师
      operationId: createTeacherInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacherRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - teacher
      summary: 获取老师列表
      operationId: getTeacherList
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeacherDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到            
    
  /teacher/{id}:
    patch:
      tags:
        - teacher
      summary: 更新老师信息
      operationId: updateTeacher
      parameters:
        - in: path
          name: id
          required: true
          description: 老师Id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacherRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    get:
      tags:
        - teacher
      summary: 获取指定老师详情
      operationId: getTeacherInfo
      parameters:
        - in: path
          name: id
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherDto'
        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
    delete:
      tags: 
        - teacher
      summary: 删除指定老师
      operationId: deleteTeacher
      parameters: 
        - in: path
          name: id
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 操作成功

        '404':
          description: 服务未找到
          content:
            application/json:
              schema:
                type: string
                default: 服务未找到
 
components:
  schemas:
    TeacherDto:
      description: 老师详情
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 老师主键
        teacherName:
          description: 老师名称
          type: string
        realName:
          description: 真实姓名
          type: string
        teacherTel:
          description: 老师联系方式
          type: string
        
    CreateTeacherRequest:
      description: 创建老师详情对象
      type: object
      properties:
        teacherName:
          description: 老师名称
          type: string
        teacherPassword:
          description: 老师密码
          type: string
        realName:
          description: 真实姓名
          type: string
        teacherTel:
          description: 老师联系方式
          type: string
      
